config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'

  resources :medicines
  resources :consultations
  resources :doctors
  resources :patients

  get '/about', to: 'pages#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultation.rb
class Consultation < ApplicationRecord
    belongs_to :doctor # indicates that method must link to db consult
    belongs_to :patient

    validates :start_time, presence: true

    validate :valid_start_end_times?
    validate :start_time_after_now?

    def valid_start_end_times?
      return unless start_time && end_time
      return if start_time.before? end_time
      errors[:start_time] << 'start_time is not before end_time'
    end

    def start_time_after_now?
      return unless start_time && end_time
      return if start_time.after? DateTime.now
      errors[:start_time] << "start_time is not before current time"
    end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :patients  # optimizes query
  has_many :consultations

  validates :name, presence: true, format: {with: /[[:alnum:]]/}
  validates :license_number, uniqueness: true, presence: true

  def presentation
    "##{license_number}: #{name}"
  end
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  validates_presence_of :name, :brand, :unit
end

app/models/patient.rb
class Patient < ApplicationRecord
  #belongs_to :doctor # <- MANDATORY FIELD
  has_many :consultations #customary belongs_to before has_many

  validates :username,
    presence: true,
    length: { minimum: 4 }

  validates :age,
    presence: true,
    numericality: {greater_than: 0, less_than: 99}

  validates :parent, presence: true, unless: :older_than_20?

  def older_than_20?
    return unless age
    age >= 21
  end

  before_save :announce_save
  after_save :log_save

  def complain(doctor_name)
    "Hey, doctor #{doctor.name}, my head hurts"
  end

  private

  def announce_save
    puts "Hey, I'm saving patient #{username} here!"
  end

  def log_save
    puts "I just saved patient #{id}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_consultation, only: %i[ show edit update destroy ]

  # GET /consultations or /consultations.json
  def index
    @consultations = Consultation.includes(:doctor, :patient).all
  end

  # GET /consultations/1 or /consultations/1.json
  def show
  end

  # GET /consultations/new
  def new
    @consultation = Consultation.new
  end

  # GET /consultations/1/edit
  def edit
  end

  # POST /consultations or /consultations.json
  def create
    @consultation = Consultation.new(consultation_params)

    respond_to do |format|
      if @consultation.save
        format.html { redirect_to @consultation, notice: "Consultation was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultations/1 or /consultations/1.json
  def update
    respond_to do |format|
      if @consultation.update(consultation_params)
        format.html { redirect_to @consultation, notice: "Consultation was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultations/1 or /consultations/1.json
  def destroy
    @consultation.destroy
    respond_to do |format|
      format.html { redirect_to consultations_url, notice: "Consultation was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultation
      @consultation = Consultation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def consultation_params
      params.require(:consultation)
        .permit(:doctor_id, :patient_id,
               :start_time, :summary, :notes)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_user!

  def index
      @doctors = Doctor.all
  end

  def new
      @doctor = Doctor.new
  end

  def create
      @doctor = Doctor.new(doctor_params)

      if @doctor.save
          redirect_to doctors_path
      else
          redirect_to new_doctor_path
      end
  end

  def edit
      @doctor = Doctor.find(params[:id])
  end

  def update
      @doctor = Doctor.find(params[:id])
      @doctor.update(doctor_params)

      redirect_to doctor_path(params[:id])
  end

  def show
      @doctor = Doctor.find(params[:id])
  end

  def destroy
      @doctor = Doctor.find(params[:id])
      @doctor.destroy

      redirect_to doctors_path
  end

  def doctor_params
      params.require(:doctor).permit(:name, :license_number)
  end
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_medicine, only: %i[ show edit update destroy ]

  # GET /medicines or /medicines.json
  def index
    @medicines = Medicine.all
  end

  # GET /medicines/1 or /medicines/1.json
  def show
  end

  # GET /medicines/new
  def new
    @medicine = Medicine.new
  end

  # GET /medicines/1/edit
  def edit
  end

  # POST /medicines or /medicines.json
  def create
    @medicine = Medicine.new(medicine_params)

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: "Medicine was successfully created." }
        format.json { render :show, status: :created, location: @medicine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicines/1 or /medicines/1.json
  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to @medicine, notice: "Medicine was successfully updated." }
        format.json { render :show, status: :ok, location: @medicine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1 or /medicines/1.json
  def destroy
    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url, notice: "Medicine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medicine_params
      params.require(:medicine).permit(:name, :brand, :unit)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    redirect_to @patient, notice: "Patient was successfully created."
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    if @patient.update(patient_params)
      redirect_to @patient, notice: "Patient was successfully updated."
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    redirect_to patients_url, notice: "Patient was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:username, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/consultations/_form.html.erb
<%= form_with(model: consultation, local: true) do |form| %>
  <% if consultation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consultation.errors.count, "error") %> prohibited this consultation from being saved:</h2>

      <ul>
        <% consultation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :doctor %>
    <%= select('consultation', 'doctor_id', Doctor.all.pluck(:name, :id))%>
  </div>

  <div class="field">
    <%= form.label :patient %>
    <%= select('consultation', 'patient_id', Patient.all.pluck(:username, :id), selected: params[:patient_id])%>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.time_field(:start_time, value: Time.now)%>
  </div>
  
    <div>
      <ul>
      <ul>
      <ul>
      <ul>
      <%= form.submit %>
    </div>
<% end %>

app/views/consultations/edit.html.erb
<h1>Editing Consultation</h1>

<%= render 'form', consultation: @consultation %>

<%= link_to 'Show', @consultation %> |
<%= link_to 'Back', consultations_path %>

app/views/consultations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Consultations</h1>

<table>
  <thead>
    <tr>
      <th>Patient</th>
      <th>Doctor</th>
      <th>Start Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consultations.each do |consultation| %>
      <tr>
        <td><%= consultation.patient.username %></td>
        <td><%= consultation.doctor.name %></td>
        <td><%= consultation.start_time.to_s(:long_ordinal) %></td>
        <td><%= link_to 'Show', consultation %></td>
        <td><%= link_to 'Edit', edit_consultation_path(consultation) %></td>
        <td><%= link_to 'Destroy', consultation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consultation', new_consultation_path %>

app/views/consultations/new.html.erb
<h1>New Consultation</h1>

<%= render 'form', consultation: @consultation %>

<%= link_to 'Back', consultations_path %>

app/views/consultations/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Consultation on <%= @consultation.start_time.to_s(:long_ordinal) %></h1>

<table>
  <thead>
    <tr>
      <th>Patient</th>
      <th>Doctor</th>
      <th>Start Time</th>
    </tr>
  </thead>

  <tbody>
  
      <tr>
        <td><%= Patient.find(@consultation.patient_id).username %></td>
        <td><%= Doctor.find(@consultation.doctor_id).name %></td>
        <td><%= @consultation.start_time.to_s(:long_ordinal) %></td>
      </tr>
  
  </tbody>
</table>

<%= link_to 'Edit', edit_consultation_path(@consultation) %> |
<%= link_to 'Back', consultations_path %>

app/views/doctors/edit.html.erb
<h1>Editing <%= @doctor.name %></h1>

<%= form_for @doctor do |f| %>
  <p>
    <label>Name</label><br />
    <%= f.text_field :name %>
  </p>

  <p>
  <label>License Number</label><br />
    <%= f.text_field :license_number %>
  </p>

  <p><%= f.submit 'Save' %></p>
<% end %>

app/views/doctors/index.html.erb
<h1>Doctors List</h1>

<p>
<%= link_to "Add a new doctor", new_doctor_path%>
</p>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>License Number</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @doctors.each do |doctor| %>
            <tr>
            <td><%= doctor.name %></td>
            <td><%= doctor.license_number %></td>
            <td><%= link_to "edit", edit_doctor_path(doctor) %></td>
            <td><%= link_to "delete", doctor_path(doctor), data: {confirm: "Are you sure?"}, method: :delete %></td>
            </tr>
        <% end %>
    </tbody>


</table>

app/views/doctors/new.html.erb
<h1>New Doctor Registration</h1>

<%= form_for @doctor do |f| %>
    <p>
        <label>Name</label></br>
        <%= f.text_field :name %>
    </p>

    <p>
        <label>License Number</label></br>
        <%= f.text_field :license_number %>
    </p>

    <p>
        <%= f.submit 'Submit New Doctor' %>
    </p>

<% end %>

app/views/doctors/show.html.erb
<p><%= link_to "back", doctors_path %></p>
<h1><%= @doctor.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseClinic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
  </head>

  <body>
    <header>
      <h1>House Clinic</h1>
      <p>A <a href="https://github.com/DavidUf11">David Ufberg</a> and <a href="https://github.com/hslzr/">Salazar</a> venture to explore Rails</p>
      <nav>
        <%= link_to "Home", root_path %>
        <%= link_to "Doctors", doctors_path %>
        <%= link_to "Patients", patients_path %>
        <%= link_to "Medicines", medicines_path %>
        <%= link_to "Consultations", consultations_path %>
      </nav>
    </header>
    <main>
      <% # This is where our views content goes %>
      <%= yield %>
    </main>
    <footer>
      <p>Have fun.</p>
    </footer>
  </body>
</html>

app/views/medicines/_form.html.erb
<%= form_with(model: medicine, local: true) do |form| %>
  <% if medicine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medicine.errors.count, "error") %> prohibited this medicine from being saved:</h2>

      <ul>
        <% medicine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :unit %>
    <%= select(:medicine, :unit, [["mG", "mg"],["mL", "ml"]]) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/medicines/edit.html.erb
<h1>Editing Medicine</h1>

<%= render 'form', medicine: @medicine %>

<%= link_to 'Show', @medicine %> |
<%= link_to 'Back', medicines_path %>

app/views/medicines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medicines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicines.each do |medicine| %>
      <tr>
        <td><%= medicine.name %></td>
        <td><%= medicine.brand %></td>
        <td><%= medicine.unit %></td>
        <td><%= link_to 'Show', medicine %></td>
        <td><%= link_to 'Edit', edit_medicine_path(medicine) %></td>
        <td><%= link_to 'Destroy', medicine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medicine', new_medicine_path %>

app/views/medicines/new.html.erb
<h1>New Medicine</h1>

<%= render 'form', medicine: @medicine %>

<%= link_to 'Back', medicines_path %>

app/views/medicines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @medicine.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @medicine.brand %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @medicine.unit %>
</p>

<%= link_to 'Edit', edit_medicine_path(@medicine) %> |
<%= link_to 'Back', medicines_path %>

app/views/pages/about.html.erb
<h1>About page</h1>

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/patients/_form.html.erb
<%= form_for patient do |f| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p>
      <label>Name</label></br>
      <%= f.text_field :username %>
    </p>

    <p>
      <label>Age</label></br>
      <%= f.text_field :age %>
    </p>

    <p>
      <%= f.submit "Create Patient" %>
    </p>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Age</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.username %></td>
        <td><%= patient.age %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Schedule', new_consultation_path(patient_id: patient.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>


<h1><%= @patient.username %>, <%= @patient.age %></h1>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>